name: develop

networks:
  pub-dev:
    driver: bridge

services:
  
  postgres_db:
      image: postgres:latest
      container_name: postgres
      environment:
        POSTGRES_NAME: 'postgres'
        POSTGRES_PASSWORD: '123'
        POSTGRES_DB: 'exchange'
      ports:
        - "5433:5432"
      networks:
        - pub-dev
      volumes:
        - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitMq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - pub-dev
    volumes:      
      - ./rabbitmq:/var/lib/rabbitmq

  minio:
      image: minio/minio
      container_name: minio
      
      ports:
        - "9000:9000"
        - "9001:9001"
      networks:
        - pub-dev
      volumes:
        - minio-storage:/data
      environment:
        MINIO_ROOT_USER: masoud
        MINIO_ROOT_PASSWORD: Strong#Pass#2022
      command: server /data --console-address :9001


volumes:
  postgres-data:
  minio-storage: